# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgemdeps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appname',
            field=models.CharField(default='adsf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
